// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  var to_content_type_and_body;

  to_content_type_and_body = require('keybase-bjson-core').to_content_type_and_body;

  exports.respond = function(_arg) {
    var body, code, ct, encoding, err, obj, res, _ref;
    res = _arg.res, obj = _arg.obj, encoding = _arg.encoding, code = _arg.code;
    _ref = to_content_type_and_body({
      encoding: encoding,
      obj: obj
    }), err = _ref[0], ct = _ref[1], body = _ref[2];
    if (err == null) {
      res.set({
        'Content-Type': ct
      });
      code || (code = 200);
      res.send(code, body);
    }
    return err;
  };

}).call(this);
